# SPDX-FileCopyrightText: 2025 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only

name: Nightly Clazy

on:
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-22.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.6
          cache: true

      - name: Install dependencies on Ubuntu
        run: |
          sudo apt update -qq
          sudo apt install lld valgrind clazy llvm ninja-build -y

      - uses: actions/checkout@v4

      - name: Configure project
        run: cmake -S . -B ./build-clazy6 --preset clazy6

      - name: Clazy
        run: cmake --build ./build-clazy6
